// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spindle.Persistence.EFCore;

#nullable disable

namespace Spindle.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(SpindleDbContext))]
    [Migration("20260806130542_MakeSignalPayloadsOptional")]
    partial class MakeSignalPayloadsOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.ExecutionHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExecutionHistories", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowDefinitionEntity", b =>
                {
                    b.Property<string>("FlowName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FlowVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FlowName", "FlowVersion");

                    b.ToTable("FlowDefinitions", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowInstanceEntity", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FlowVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Input", "Spindle.Persistence.EFCore.Entities.FlowInstanceEntity.Input#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Input_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Input_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Input_TypeName");
                        });

                    b.HasKey("InstanceId");

                    b.HasIndex("FlowName", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("FlowInstances", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.InboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "Spindle.Persistence.EFCore.Entities.InboxMessageEntity.Payload#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_TypeName");
                        });

                    b.HasKey("MessageId");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("datetimeoffset");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "Spindle.Persistence.EFCore.Entities.OutboxMessageEntity.Payload#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_TypeName");
                        });

                    b.HasKey("MessageId");

                    b.HasIndex("PublishedAt", "CreatedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalWaitEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("SignalName", "CorrelationKey", "CompletedAt");

                    b.ToTable("SignalWaits", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepAttemptEntity", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttemptId");

                    b.ToTable("StepAttempts", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepDependencyEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DependsOnId")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FlowInstanceId", "StepId", "DependsOnId");

                    b.HasIndex("FlowInstanceId", "DependsOnId");

                    b.HasIndex("FlowInstanceId", "StepId");

                    b.ToTable("StepDependencies");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Queue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RetryAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("FlowInstanceId", "Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("StepInstances", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepLeaseEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.ToTable("StepLeases", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.TimerEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FiredAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("FiredAt", "DueAt");

                    b.ToTable("Timers", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.ExecutionHistoryEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Payload", b1 =>
                        {
                            b1.Property<long>("ExecutionHistoryEntityId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_TypeName");

                            b1.HasKey("ExecutionHistoryEntityId");

                            b1.ToTable("ExecutionHistories");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionHistoryEntityId");
                        });

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowDefinitionEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Definition", b1 =>
                        {
                            b1.Property<string>("FlowDefinitionEntityFlowName")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("FlowDefinitionEntityFlowVersion")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Definition_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Definition_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Definition_TypeName");

                            b1.HasKey("FlowDefinitionEntityFlowName", "FlowDefinitionEntityFlowVersion");

                            b1.ToTable("FlowDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("FlowDefinitionEntityFlowName", "FlowDefinitionEntityFlowVersion");
                        });

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowInstanceEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Result", b1 =>
                        {
                            b1.Property<string>("FlowInstanceEntityInstanceId")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Result_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Result_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Result_TypeName");

                            b1.HasKey("FlowInstanceEntityInstanceId");

                            b1.ToTable("FlowInstances");

                            b1.WithOwner()
                                .HasForeignKey("FlowInstanceEntityInstanceId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Payload", b1 =>
                        {
                            b1.Property<int>("SignalEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Payload_TypeName");

                            b1.HasKey("SignalEntityId");

                            b1.ToTable("Signals");

                            b1.WithOwner()
                                .HasForeignKey("SignalEntityId");
                        });

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepDependencyEntity", b =>
                {
                    b.HasOne("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", "DependsOn")
                        .WithMany("Dependents")
                        .HasForeignKey("FlowInstanceId", "DependsOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", "Step")
                        .WithMany("Dependencies")
                        .HasForeignKey("FlowInstanceId", "StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Input", b1 =>
                        {
                            b1.Property<string>("StepInstanceEntityFlowInstanceId")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("StepInstanceEntityStepId")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Input_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Input_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Input_TypeName");

                            b1.HasKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");

                            b1.ToTable("StepInstances");

                            b1.WithOwner()
                                .HasForeignKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");
                        });

                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Result", b1 =>
                        {
                            b1.Property<string>("StepInstanceEntityFlowInstanceId")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("StepInstanceEntityStepId")
                                .HasColumnType("nvarchar(255)");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Result_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Result_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Result_TypeName");

                            b1.HasKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");

                            b1.ToTable("StepInstances");

                            b1.WithOwner()
                                .HasForeignKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");
                        });

                    b.Navigation("Input");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
