// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spindle.Persistence.EFCore;

#nullable disable

namespace Spindle.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(SpindleDbContext))]
    partial class SpindleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.ExecutionHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExecutionHistories");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowDefinitionEntity", b =>
                {
                    b.Property<string>("FlowName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FlowVersion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("FlowName", "FlowVersion");

                    b.ToTable("FlowDefinitions");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowInstanceEntity", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FlowVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("InstanceId");

                    b.HasIndex("FlowName", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("FlowInstances");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.InboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId");

                    b.HasIndex("PublishedAt", "CreatedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaisedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalWaitEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("SignalName", "CorrelationKey", "CompletedAt");

                    b.ToTable("SignalWaits");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepAttemptEntity", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttemptId");

                    b.ToTable("StepAttempts");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Queue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("StepInstances");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepLeaseEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("AcquiredAt")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.ToTable("StepLeases");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.TimerEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("DueAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("FiredAt")
                        .HasColumnType("bigint");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("FiredAt", "DueAt");

                    b.ToTable("Timers");
                });
#pragma warning restore 612, 618
        }
    }
}
