// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spindle.Persistence.EFCore;

#nullable disable

namespace Spindle.Persistence.EFCore.Sqlite.Migrations
{
    [DbContext(typeof(SpindleDbContext))]
    partial class SpindleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.ExecutionHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExecutionHistories", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowDefinitionEntity", b =>
                {
                    b.Property<string>("FlowName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowVersion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlowName", "FlowVersion");

                    b.ToTable("FlowDefinitions", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowInstanceEntity", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowVersion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Input", "Spindle.Persistence.EFCore.Entities.FlowInstanceEntity.Input#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Input_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Input_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Input_TypeName");
                        });

                    b.HasKey("InstanceId");

                    b.HasIndex("FlowName", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("FlowInstances", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.InboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceivedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "Spindle.Persistence.EFCore.Entities.InboxMessageEntity.Payload#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_TypeName");
                        });

                    b.HasKey("MessageId");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "Spindle.Persistence.EFCore.Entities.OutboxMessageEntity.Payload#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_TypeName");
                        });

                    b.HasKey("MessageId");

                    b.HasIndex("PublishedAt", "CreatedAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RaisedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "Spindle.Persistence.EFCore.Entities.SignalEntity.Payload#SerializedPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_TypeName");
                        });

                    b.HasKey("Id");

                    b.ToTable("Signals", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.SignalWaitEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("SignalName", "CorrelationKey", "CompletedAt");

                    b.ToTable("SignalWaits", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepAttemptEntity", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AttemptId");

                    b.ToTable("StepAttempts", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DispatchMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Queue")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetryAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("StepInstances", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepLeaseEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("AcquiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.ToTable("StepLeases", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.TimerEntity", b =>
                {
                    b.Property<string>("FlowInstanceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DueAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FiredAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlowInstanceId", "StepId");

                    b.HasIndex("FiredAt", "DueAt");

                    b.ToTable("Timers", (string)null);
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.ExecutionHistoryEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Payload", b1 =>
                        {
                            b1.Property<long>("ExecutionHistoryEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Payload_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Payload_TypeName");

                            b1.HasKey("ExecutionHistoryEntityId");

                            b1.ToTable("ExecutionHistories");

                            b1.WithOwner()
                                .HasForeignKey("ExecutionHistoryEntityId");
                        });

                    b.Navigation("Payload");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowDefinitionEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Definition", b1 =>
                        {
                            b1.Property<string>("FlowDefinitionEntityFlowName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FlowDefinitionEntityFlowVersion")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Definition_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Definition_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Definition_TypeName");

                            b1.HasKey("FlowDefinitionEntityFlowName", "FlowDefinitionEntityFlowVersion");

                            b1.ToTable("FlowDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("FlowDefinitionEntityFlowName", "FlowDefinitionEntityFlowVersion");
                        });

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.FlowInstanceEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Result", b1 =>
                        {
                            b1.Property<string>("FlowInstanceEntityInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Result_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_TypeName");

                            b1.HasKey("FlowInstanceEntityInstanceId");

                            b1.ToTable("FlowInstances");

                            b1.WithOwner()
                                .HasForeignKey("FlowInstanceEntityInstanceId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Spindle.Persistence.EFCore.Entities.StepInstanceEntity", b =>
                {
                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Input", b1 =>
                        {
                            b1.Property<string>("StepInstanceEntityFlowInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("StepInstanceEntityStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Input_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Input_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Input_TypeName");

                            b1.HasKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");

                            b1.ToTable("StepInstances");

                            b1.WithOwner()
                                .HasForeignKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");
                        });

                    b.OwnsOne("Spindle.Abstractions.Snapshot.SerializedPayload", "Result", b1 =>
                        {
                            b1.Property<string>("StepInstanceEntityFlowInstanceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("StepInstanceEntityStepId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_ContentType");

                            b1.Property<byte[]>("Data")
                                .IsRequired()
                                .HasColumnType("BLOB")
                                .HasColumnName("Result_Data");

                            b1.Property<string>("TypeName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Result_TypeName");

                            b1.HasKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");

                            b1.ToTable("StepInstances");

                            b1.WithOwner()
                                .HasForeignKey("StepInstanceEntityFlowInstanceId", "StepInstanceEntityStepId");
                        });

                    b.Navigation("Input");

                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
